pipeline{
    agent any
    tools{
        maven 'M2_HOME'
    }

    stages{
        stage('maven'){
            steps{
                sh 'mvn clean validate compile install test package' 
            }
        }
        stage('upload artifact'){
            steps{
                sh 'curl -uadmin:AP7urdiCeU6TTGNQ4qYzZLk4e2X -T \
                target/bio*.jar \
                "http://ec2-44-202-108-32.compute-1.amazonaws.com:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"'
            }

        }
    } 
                    
}