pipeline{
    agent any
    tools{
        maven 'M2_HOME'
    }

    stages{
        stage(sonar-scan){
            steps{
                sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=EsthaDevops2022_geo-app'
            }
        }

        stage('maven'){
            steps{
                sh 'mvn clean'
                sh 'mvn validate'
                sh 'mvn compile' 
                sh 'mvn install' 
                sh 'mvn test'  
                sh 'mvn package'
            }
        }
        stage('upload artifact'){
            steps{
                sh 'curl -uadmin:AP7urdiCeU6TTGNQ4qYzZLk4e2X -T \
                target/bio*.jar \
                "http://ec2-44-202-230-69.compute-1.amazonaws.com:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"'
            }

        }
    } 
                    
}